# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: sellout/flaky:base/.github/settings.yml

# See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
repository:
  name: flaky
  description: Templates for dev environments
  # homepage: https://example.github.io/
  topics: development, hacktoberfest, nix-flakes, nix-templates

branches:
  - name: main
    # https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection
    protection:
      required_status_checks:
        contexts:
          - "check format [aarch64-darwin]"
          - "check format [aarch64-linux]"
          - "check format [x86_64-linux]"
          - "devShell bash [aarch64-darwin]"
          - "devShell bash [aarch64-linux]"
          - "devShell bash [x86_64-linux]"
          - "devShell c [aarch64-darwin]"
          - "devShell c [aarch64-linux]"
          - "devShell c [x86_64-linux]"
          - "devShell default [aarch64-darwin]"
          - "devShell default [aarch64-linux]"
          - "devShell default [x86_64-linux]"
          - "devShell emacs-lisp [aarch64-darwin]"
          - "devShell emacs-lisp [aarch64-linux]"
          - "devShell emacs-lisp [x86_64-linux]"
          - "devShell haskell [aarch64-darwin]"
          - "devShell haskell [aarch64-linux]"
          - "devShell haskell [x86_64-linux]"
          - "devShell nix [aarch64-darwin]"
          - "devShell nix [aarch64-linux]"
          - "devShell nix [x86_64-linux]"
          - "devShell rust [aarch64-darwin]"
          - "devShell rust [aarch64-linux]"
          - "devShell rust [x86_64-linux]"
          - "devShell scala [aarch64-darwin]"
          - "devShell scala [aarch64-linux]"
          - "devShell scala [x86_64-linux]"
