# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: sellout/flaky:base/.github/settings.yml

# See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
repository:
  name: {{project.name}}
  description: {{project.summary}}
  # homepage: https://example.github.io/
  # topics: development, nix-flakes, nix-templates

branches:
  - name: main
    # https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection
    protection:
      required_status_checks:
        contexts:
          - "check elisp-doctor [aarch64-darwin]"
          - "check elisp-doctor [aarch64-linux]"
          - "check elisp-doctor [x86_64-linux]"
          - "check elisp-lint [aarch64-darwin]"
          - "check elisp-lint [aarch64-linux]"
          - "check elisp-lint [x86_64-linux]"
          - "check format [aarch64-darwin]"
          - "check format [aarch64-linux]"
          - "check format [x86_64-linux]"
          - "devShell default [aarch64-darwin]"
          - "devShell default [aarch64-linux]"
          - "devShell default [x86_64-linux]"
          - "homeConfig aarch64-darwin-bradix-example"
          - "homeConfig aarch64-linux-bradix-example"
          - "homeConfig x86_64-linux-bradix-example"
          - "package default [aarch64-darwin]"
          - "package default [aarch64-linux]"
          - "package default [x86_64-linux]"
          - "package emacs-{{project.name}} [aarch64-darwin]"
          - "package emacs-{{project.name}} [aarch64-linux]"
          - "package emacs-{{project.name}} [x86_64-linux]"
