title: Documentation for Flaky-based projects
description: Shared documents that apply to all projects.
mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.14.0"
plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs@v0.12.0
