# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: sellout/flaky:base/.github/settings.yml

# See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
repository:
  name: {{project.name}}
  description: {{project.summary}}
  homepage: https://sellout.github.io/{{project.name}}
  topics: dhall, hacktoberfest, library

branches:
  - name: main
    # https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection
    protection:
      required_status_checks:
        contexts:
          - "check format [aarch64-darwin]"
          - "check format [aarch64-linux]"
          - "check format [x86_64-linux]"
          - "devShell default [aarch64-darwin]"
          - "devShell default [aarch64-linux]"
          - "devShell default [x86_64-linux]"
          - "homeConfiguration aarch64-darwin-{{project.name}}-example"
          - "homeConfiguration aarch64-linux-{{project.name}}-example"
          - "homeConfiguration x86_64-linux-{{project.name}}-example"
          - "package default [aarch64-darwin]"
          - "package default [aarch64-linux]"
          - "package default [x86_64-linux]"
          - "package {{project.name}} [aarch64-darwin]"
          - "package {{project.name}} [aarch64-linux]"
          - "package {{project.name}} [x86_64-linux]"

pages:
  build_type: "workflow"
  source:
    branch: "main"
