#+title: {{project.name}}

{{project.summary}}

{{project.description}}

* usage

* development environment

We recommend the following steps to make working in this repo as easy as possible.

** ~direnv allow~

This command ensures that any work you do within this repo is done within a consistent reproducible environment. That environment provides various debugging tools, etc. When you leave this directory, you will leave that environment behind, so it doesn’t impact anything else on your system.

** ~git config --local include.path ../.config/git/config~

This will apply our repo-specific Git configuration to ~git~ commands run against this repo. It is very lightweight (you should definitely look at it before applying this command) – it does things like telling ~git blame~ to ignore formatting-only commits.

* building

** preferred

Especially if you are unfamiliar with the Emacs ecosystem, there is a flake-based Nix build.

** traditional

This project is built with [[https://doublep.github.io/eldev/][Eldev]].
